import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;
import 'dart:io';

part 'database.g.dart'; // generated by build_runner

// Local SQLite is the SOURCE OF TRUTH on device (§13.1). The app writes here first and
// never blocks on the network; the Outbox holds pending mutations for the sync worker.

class DailyReportsLocal extends Table {
  TextColumn get id => text()();            // client-generated UUIDv7 (§13.2)
  TextColumn get projectId => text()();
  DateTimeColumn get reportDate => dateTime()();
  TextColumn get workSummary => text()();
  TextColumn get weather => text().nullable()();
  TextColumn get issues => text().nullable()();
  TextColumn get buildingId => text().nullable()();
  RealColumn get lon => real().nullable()();
  RealColumn get lat => real().nullable()();
  TextColumn get idempotencyKey => text()();  // enforced unique on the server
  BoolColumn get synced => boolean().withDefault(const Constant(false))();
  @override
  Set<Column> get primaryKey => {id};
}

// Photos queue SEPARATELY with their own retry (§13.4): a report is visible once its
// thumbs upload; originals continue in the background.
class MediaLocal extends Table {
  TextColumn get id => text()();
  TextColumn get reportId => text().nullable()();
  TextColumn get localThumbPath => text()();
  TextColumn get localDisplayPath => text()();
  TextColumn get localOriginalPath => text()();
  RealColumn get lon => real().nullable()();
  RealColumn get lat => real().nullable()();
  DateTimeColumn get capturedAt => dateTime()();
  TextColumn get phashHex => text().nullable()();
  BoolColumn get mockLocation => boolean().withDefault(const Constant(false))();
  TextColumn get uploadState => text().withDefault(const Constant('pending'))(); // pending|thumb|display|original|done
  @override
  Set<Column> get primaryKey => {id};
}

// The outbox: one row per pending mutation. Drained on reconnect; retried with backoff.
class Outbox extends Table {
  IntColumn get seq => integer().autoIncrement()();
  TextColumn get kind => text()();            // 'submit_report' | 'register_media'
  TextColumn get refId => text()();           // report or media id
  TextColumn get payloadJson => text()();
  IntColumn get attempts => integer().withDefault(const Constant(0))();
  DateTimeColumn get nextAttemptAt => dateTime().nullable()();
}

@DriftDatabase(tables: [DailyReportsLocal, MediaLocal, Outbox])
class AppDb extends _$AppDb {
  AppDb() : super(_open());
  @override
  int get schemaVersion => 1;

  Future<void> enqueue(String kind, String refId, String payloadJson) =>
      into(outbox).insert(OutboxCompanion.insert(kind: kind, refId: refId, payloadJson: payloadJson));

  Future<List<OutboxData>> dueOutbox(DateTime now) => (select(outbox)
        ..where((o) => o.nextAttemptAt.isSmallerOrEqualValue(now) | o.nextAttemptAt.isNull())
        ..orderBy([(o) => OrderingTerm.asc(o.seq)]))
      .get();
}

LazyDatabase _open() => LazyDatabase(() async {
      final dir = await getApplicationDocumentsDirectory();
      return NativeDatabase(File(p.join(dir.path, 'sitelens.sqlite')));
    });
